INSERT INTO Livro (titulo,autor,status) VALUES('A arte da guerra','Sun Tzu','DISPONIVEL')
INSERT INTO Livro (titulo,autor,status) VALUES('Harry Potter e a Pedra Filosofal','J.K. Rowling','DISPONIVEL')
INSERT INTO Livro (titulo,autor,status) VALUES('Neuromancer','William Gibson','DISPONIVEL')
INSERT INTO Livro (titulo,autor,status) VALUES('Harry Potter e a Câmara Secreta','J.K. Rowling','DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('Dom Casmurro', 'Machado de Assis', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('O Senhor dos Anéis', 'J.R.R. Tolkien', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('1984', 'George Orwell', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('A Revolução dos Bichos', 'George Orwell', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('A Metamorfose', 'Franz Kafka', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('Brave New World', 'Aldous Huxley', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('O Alquimista', 'Paulo Coelho', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('O Morro dos Ventos Uivantes', 'Emily Brontë', 'DISPONIVEL')
INSERT INTO livro (titulo,autor,status) VALUES('Orgulho e Preconceito', 'Jane Austen', 'DISPONIVEL')